// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCx_uPwfmSWYauvDw-zZQsbe6NryXhe6mM',
    appId: '1:1062937223093:android:5cf8a10a1a5063510003fc',
    messagingSenderId: '1062937223093',
    projectId: 'hahaha-79a4a',
    storageBucket: 'hahaha-79a4a.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDn-tLLQdV7nEzUPoF9o8iOEuYqSjc7cSo',
    appId: '1:1062937223093:web:bed2ed30df966e000003fc',
    messagingSenderId: '1062937223093',
    projectId: 'hahaha-79a4a',
    authDomain: 'hahaha-79a4a.firebaseapp.com',
    storageBucket: 'hahaha-79a4a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBENca804HDl2uJ588z4Gm1ek-w4wnHEqY',
    appId: '1:1062937223093:ios:e578e15b088589510003fc',
    messagingSenderId: '1062937223093',
    projectId: 'hahaha-79a4a',
    storageBucket: 'hahaha-79a4a.firebasestorage.app',
    iosBundleId: 'com.example.trainSystem',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDn-tLLQdV7nEzUPoF9o8iOEuYqSjc7cSo',
    appId: '1:1062937223093:web:85bb4fc7dfc536830003fc',
    messagingSenderId: '1062937223093',
    projectId: 'hahaha-79a4a',
    authDomain: 'hahaha-79a4a.firebaseapp.com',
    storageBucket: 'hahaha-79a4a.firebasestorage.app',
  );

}